services:
  postgres:
    image: ${POSTGRES_IMAGE:-postgres:15}
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    container_name: ${POSTGRES_CONTAINER_NAME:-simplewallet-postgres-db}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - simplewallet-prod-network

  app:
    image: eps364/simplewallet-backend:latest
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    container_name: simplewallet-backend
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      # Application configuration
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      APP_NAME: ${APP_NAME}
      
      # Server configuration
      PORT: ${PORT:-8080}
      
      # Database configuration
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
      # Hibernate/JPA configuration
      HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO:-validate}
      SHOW_SQL: ${SHOW_SQL:-false}
      
      # Logging configuration
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      WEB_LOG_LEVEL: ${WEB_LOG_LEVEL:-WARN}
      SQL_LOG_LEVEL: ${SQL_LOG_LEVEL:-WARN}
      SQL_PARAM_LOG_LEVEL: ${SQL_PARAM_LOG_LEVEL:-WARN}
      
      # Security configuration
      JWT_SECRET: ${JWT_SECRET}
      
      # Additional configuration
      SHOW_ALL_VARIABLES: ${SHOW_ALL_VARIABLES:-false}
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - app_logs:/app/logs
    networks:
      - simplewallet-prod-network

volumes:
  postgres_data:
    driver: local
  app_logs:
    driver: local

networks:
  simplewallet-prod-network:
    driver: bridge
