# Configuração do profile de teste
spring:
  # Configuração do banco de dados H2 em memória para testes
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  # Configuração JPA/Hibernate para testes
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false

  # Desabilitar Docker Compose para testes
  docker:
    compose:
      enabled: false

# Configuração de logging para testes (menos verboso)
logging:
  level:
    br.dev.mission.simplewallet: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    root: WARN

# Desabilitar endpoints de management em testes
management:
  endpoints:
    enabled-by-default: false
