name: Build and Push Database Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/src/main/resources/db/**'
      - 'backend/Dockerfile.db'
  pull_request:
    branches: [ main ]
    types: [ closed ]
    paths:
      - 'backend/src/main/resources/db/**'
      - 'backend/Dockerfile.db'
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: eps364/simplewallet-db

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Só executa se o PR foi mergeado ou se for push direto na main
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: List database files
      run: |
        echo "Database migration files:"
        find backend/src/main/resources/db -type f -name "*.sql" 2>/dev/null || echo "No migration files found"
        echo "Dockerfile.db exists:"
        ls -la backend/Dockerfile.db

    - name: Set up QEMU (multiplatform)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha
        flavor: |
          latest=auto

    - name: Build and push Database Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile.db
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
